server: 
     port: 8080
     
app: 
    name: My App
    description: Welcome to ${app.name}

my: 
  greeting: Hello World!
  list: 
      values: One,Two,Three
      
dbValues: "{connectionString: 'https://-----',username: 'usrname',password: 'passwd'}"

db: 
  connection: dev-connection-string-here
  host: 128.0.0.1
  port: 1300

#<!--  below property is used for actuator -->
management: 
   endpoints: 
    web: 
     exposure: 
       include: "*"

spring.profiles.active: test